### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by karldanninger** [royGil/accounts-react#11]
It's very difficult to use this package without a clear example repo of this working. I'm having a hard time getting this set up at all.  It seems that whenever the button is clicked in the form, it refreshes the page.

**Comment by royGil** [comment]
Hey,
Can you elaborate on what wasn't clear about setting it up?
I think the documentation covers everything but maybe I've missed something..

You can find a working example [here](https://github.com/royGil/accounts-react-demo) and a demo [here](https://react-accounts-demo.herokuapp.com/)

**Comment by remingtonchan** [comment]
@royGil 

Hi! I'm currently trying to make the demo repo work and I'm encountering this issue:

```

/Users/remingtonchan/.meteor/packages/meteor-tool/.1.6.1_1.miu6iq.obrij++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at service-config.js (server/config/service-config.js:4:8)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

This is after running `meteor npm install @babel/runtime@7.0.0-beta.55` to make babel/runtime work on Meteor 1.7.

Any leads on how to resolve this issue? I'm super stoked to use your package in my project as a cleaner and easier way to integrate user accounts!

Hope to hear from you soon!

**Comment by inspiraluna** [comment]
@remingtonchan hey, update to Meteor 1.8.1 and use latest @babel/runtime@latest

**Comment by karldanninger** [comment]
Thanks!
