### ISSUE TITLE
showResendVerificationLink functionality

### ISSUE THREAD

**Issue by pixlol** [royGil/accounts-react#12]
Hi,
I have happily started using this great package, helping us to fully embrace react in the meteor world. Many thanks for creating and sharing it!
What puzzles me ist the missing resend verification link. I can`t find it anywhere. 
Could you please tell me in which use-case it should be displayed?  TIA

**Comment by SupaMic** [comment]
I have been puzzling on the same thing for a few days and after I did a deep dive on the meteoreact:accounts package I found that the package that Meteor added is not as up to date as this Github Repo is so it is missing all the code for resendVerification including state, routes (mapStateToRoute), fields and probably more.   Go to the Atmosphere page to see the more accurate meteor package and feature docs: https://atmospherejs.com/meteoreact/accounts

**Comment by pixlol** [comment]
Thank for pointing this out. We will try this, when working on the login stuff again. I will close this, as it is not an issue of this package.
