### ISSUE TITLE
Incorrect styled package names in readme

### ISSUE THREAD

**Issue by cur33** [royGil/accounts-react#9]
I was unable to install `meteoreact:semantic-ui` as it's called in the readme, but `meteor add meteoreact:accounts-semantic` worked. I noticed that `meteoreact:unstyled-ui` should also be renamed to `meteoreact:accounts-unstyled`.

**Comment by royGil** [comment]
Thanks! I've updated the guide

**Comment by cur33** [comment]
Awesome! And I think all thanks go to you for creating this accounts UI. I'm not new to development, but I _am_ new to both React and Meteor, so having this available saved me a lot of time in this project I'm starting. They should really use your component in the Meteor React tutorial instead of that annoying wrapper around the Blaze accounts-ui component. I couldn't even get that to compile when I did the tutorial.

**Comment by royGil** [comment]
I'm really happy to hear that :)

By the way, was there anything unclear about how to use the package?
